[#33] Fix pipeline failure in the Octo module
The pipeline is currently failing due to the following message:
```
1) Octo Module Tests
       Selecting the table CUSTOMERS from the tables list:
     TypeError: Cannot read property 'click' of null
```
This error is happening because the database doesn't seem to be set correctly for OCTO tables to be populated.
```
[ERROR] Null subscripts must be enabled for database file [/home/aa/mumps.dat] : region [DEFAULT] (global ^%ydboctoxref maps to this region)
[ERROR] /tmp/tmp.hRVxLeqGgh/YDBOcto-master/src/octo_init.c:834 2021-11-21 10:54:30 : ERR_NULL_SUBS_DISABLED : Null subscripts must be enabled for proper operation. Please set '-null_subscripts=always' for all regions containing Octo global variables.
```

The fix is to include the configuration for the octo tables in ```octo_setup.sh```